# Generated by Django 5.0.6 on 2024-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('marca_producto', models.CharField(max_length=50)),
                ('modelo_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField(max_length=300)),
                ('precio_producto', models.FloatField()),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
