# Generated by Django 5.0.6 on 2024-06-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_producto_delete_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion_producto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca_producto',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='modelo_producto',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_producto',
            new_name='precio',
        ),
    ]
